# Generated by Django 2.0.3 on 2018-04-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormExample', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
