# Generated by Django 2.0.3 on 2018-04-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormExample', '0002_auto_20180406_1243'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='CUSTOMER',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='EMPLOYEE',
        ),
    ]
