# Generated by Django 2.0.3 on 2018-04-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormExample', '0003_auto_20180406_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
    ]
