# Generated by Django 2.0.3 on 2018-05-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormExample', '0003_headtoheadmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='pps',
        ),
    ]
