# Generated by Django 2.0.3 on 2018-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormExample', '0004_remove_customer_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('entryfee', models.IntegerField(default=0)),
                ('totalprizes', models.IntegerField(default=0)),
                ('entry', models.IntegerField(default=0)),
                ('entries', models.IntegerField(default=0)),
                ('live', models.DateTimeField(verbose_name='time contest finishes')),
            ],
            options={
                'db_table': 'Contest',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
