# Generated by Django 2.0.3 on 2018-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormExample', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('shares', models.IntegerField(default=0)),
                ('pps', models.IntegerField(default=0)),
            ],
        ),
    ]
