# Generated by Django 2.0.3 on 2018-05-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormExample', '0007_stock'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stock',
            table='Stock',
        ),
    ]
