# Generated by Django 2.0.3 on 2018-05-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormExample', '0008_auto_20180508_1440'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contest',
            table='Contest',
        ),
    ]
