# Generated by Django 2.0.3 on 2018-05-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormExample', '0009_auto_20180508_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('shares', models.IntegerField(default=0)),
                ('pps', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'StockEntry',
            },
        ),
    ]
