# Generated by Django 2.0.3 on 2018-05-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormExample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headtoheadmatch',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='headtoheadmatch',
            name='user2',
        ),
        migrations.DeleteModel(
            name='HeadToHeadMatch',
        ),
    ]
